# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='belt_exam_app.User'),
            preserve_default=False,
        ),
    ]
